spring:
  jpa:
    show-sql: true
    hibernate:
      #ddlAuto: validate
      ddlAuto: create-drop
  #sql:
   # init:
    #  mode: embedded
  h2:
    console:
      enabled: true
      path: /h2console
  datasource:
    url: jdbc:h2:mem:test;DATABASE_TO_UPPER=false
    username: admin
    password: admin

