spring:
  jpa:
    show-sql: true
    hibernate:
      ddlAuto: none
  sql:
    init:
      mode: embedded #embedded works only with builtin DB, for MySql use #always
  h2:
    console:
      enabled: true
      path: /h2console
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;DATABASE_TO_UPPER=false
    username: admin
    password: admin
  liquibase:
    contexts: dev