spring:
  liquibase:
    change-log: classpath:db/master.xml
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
server:
  servlet:
    context-path: /library
    session:
      timeout: 1440
      cookie:
        max-age: 86400
  port: 8080